# Generated by Django 6.0.7 on 2026-07-21 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inner_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('inner_width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('inner_height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='packing.OrderItem', to='packing.product'),
        ),
    ]
