# Generated by Django 6.0.7 on 2026-07-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_order_recommended_box_order_status_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recommended_box',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
